FROM gradle:jdk17

RUN apt-get update && apt-get install -y dumb-init

WORKDIR /usr/app

COPY ./entrypoint.sh ./

EXPOSE 8080

ENTRYPOINT [ "/usr/bin/dumb-init", "--" ]

CMD [ "/bin/sh", "./entrypoint.sh" ]