services:
  blue:
    container_name: blue
    image: habitpay/backend:${version}
    ports:
      - "8080:8080"
    restart: on-failure:3
    healthcheck:
      test: "wget --quiet --spider localhost:8080/actuator/health || exit 1"
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 30
    env_file:
      - ./env/.env.prod
    networks:
      - backend-connection

  green:
    container_name: green
    image: habitpay/backend:${version}
    ports:
      - "8081:8080"
    restart: on-failure:3
    healthcheck:
      test: "wget --quiet --spider localhost:8080/actuator/health || exit 1"
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 30
    env_file:
      - ./env/.env.prod
    networks:
      - backend-connection

networks:
  backend-connection:
    driver: bridge