spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
#    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    url: jdbc:postgresql://localhost:5432/postgres
#    username: ${POSTGRES_USER}
    username: postgres
#    password: ${POSTGRES_PASSWORD}
    password:
  devtools:
    livereload:
      enabled: true

jwt:
  issuer: hello@world.kr
  secret: 1234qwer