---
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope: ${GOOGLE_SCOPE}
  jpa:
    database: postgresql
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
---
spring:
  cloud:
    aws:
      s3:
        bucket: ${BUCKET_NAME}
      stack:
        auto: false
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
---
jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}
---
cors:
  allowed-origins: ${ALLOWED_ORIGINS}
---
oauth:
  redirect-url: ${REDIRECT_URL}