---
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope: ${GOOGLE_SCOPE}
  jpa:
    database: postgresql
---
cloud:
  aws:
    s3:
      bucket: cloud.aws.s3.bucket
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
---
spring:
  profiles:
    active: local
---
spring:
  profiles:
    active: prod
