== 챌린지 API
:doctype: book
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:seclinks:

챌린지 정보 조회, 챌린지 생성, 챌린지 정보 수정을 수행하는 API 목록입니다.

=== 전체 챌린지 목록 조회

전체 챌린지 목록을 조회합니다.

1페이지에 20개씩 반환합니다.

operation::challenge/get-challenge-page[snippets='http-request,http-response,response-fields']

=== 나의 챌린지 참여 목록 조회

현재 접속한 사용자가 참여하고 있는 챌린지 목록을 반환합니다.


챌린지 상태의 경우, 다음의 7가지 상태 중 하나가 문자열로 전달됩니다.

[ "SCHEDULED"(진행 예정),
"IN_PROGRESS"(진행 중),
"COMPLETED_PENDING_SETTLEMENT"(완료, 정산 안 됨),
"COMPLETED_SETTLED"(완료, 정산됨),
"CANCELED"(중도 취소),
"CANCELED_SETTLED"(중도 취소, 정산됨),
"CANCELED_BEFORE_START"(시작 전 취소함) ]

operation::challenge/get-my-challenge-list[snippets='http-request,http-response,response-fields']

=== 다른 멤버의 챌린지 참여 목록 조회

다른 멤버가 참여하고 있는 챌린지 목록을 반환합니다.

('나의 챌린지 참여 목록 조회'와 동일한 형태의 데이터를 반환합니다.)

operation::challenge/get-member-challenge-list[snippets='http-request,http-response,response-fields']

=== 챌린지 상세 정보 조회

첼린지의 상세 정보를 조회합니다.

참여 요일에 해당하는 `participatingDays` 는 비트 연산을 사용합니다.

7자리로 이루어진 2진수 `0000000` 를 기준으로 좌측부터 `일월화수목금토` 입니다.

예를 들어, `화요일`, `목요일` 이 챌린지 참여 날짜라면, 2진수로 `0010100` 이고, 10진수로 변환하면 `20` 이 됩니다.

HTTP response 예시에 나온 `participatingDays` 의 값 `4` 는 10진수 `4` 를 의미하고 2진수로 `0000011` 이기 때문에 `금요일` 과 `토요일` 이 챌린지 참여 요일이 됩니다.

operation::challenge/get-challenge-details[snippets='http-request,http-response,response-fields']

==== 에러 응답

===== 챌린지가 존재하지 않는 경우 (404 Not Found)

존재하지 않는 챌린지를 조회한 경우입니다.

operation::challenge/get-challenge-details-not-found-exception[snippets='http-request,http-response,response-fields']

=== 챌린지 등록 멤버 조회

특정 챌린지 내에 등록한 멤버들의 목록을 조회합니다.

operation::challenge/get-challenge-members[snippets='http-request,http-response,response-fields']

=== 챌린지 별 참여 기록 조회

챌린지 별 참여 기록을 조회합니다.

챌린지 별 달력의 참여 기록 표시를 위한 API입니다.

'참여 성공 날짜 목록', '참여 실패 날짜 목록', '앞으로 참여할 예정인 날짜 목록'의 세 가지 데이터가 제공됩니다.

ZoneId가 없는 날짜 데이터(시간 정보 없음)이기 때문에, 시간대 변환 없이 바로 사용할 수 있습니다.

'API 요청일'과 '참여일'이 동일한 경우, 이미 참여했다면 성공 목록에, 아직 참여하지 않았다면 예정 목록에 담기게 됩니다.

operation::challenge/get-challenge-records[snippets='http-request,http-response,response-fields']

=== 챌린지 생성

새로운 첼린지를 생성합니다.

operation::challenge/create-challenge[snippets='http-request,http-response,response-fields']

==== 에러 응답

===== 챌린지 시작 시간이 현재 시간보다 이전인 경우 (400 Bad Request)

챌린지 시작 시간이 현재 시간보다 이전인 경우입니다.

operation::challenge/create-challenge-invalid-start-time[snippets='http-request,http-response,response-fields']

===== 챌린지 진행 기간에 참여 요일이 포함되지 않은 경우 (400 Bad Request)

챌린지 진행 기간에 선택한 참여 요일이 전혀 포함되지 않은 경우입니다.

예시

- 진행 기간: 2024.10.07(월) ~ 2024.10.08(화)
- 참여 요일: 수요일

operation::challenge/create-challenge-invalid-participating-days[snippets='http-request,http-response,response-fields']

=== 챌린지 정산

종료된 챌린지의 상태를 정산 완료로 변경합니다.

operation::challenge/settlement[snippets='http-request,http-response,response-fields']

=== 챌린지 정보 수정

챌린지 정보를 수정합니다.

operation::challenge/patch-challenge[snippets='http-request,http-response,response-fields']

==== 에러 응답

===== 챌린지 설명이 이전과 동일한 경우 (400 Bad Request)

챌린지 설명이 이전과 동일한 경우입니다.

operation::challenge/patch-challenge-duplicated-description-exception[snippets='http-request,http-response,response-fields']

===== 챌린지 주최자가 아닌 경우 (403 Forbidden)

챌린지 주최자가 아닌 경우입니다.

operation::challenge/patch-challenge-forbidden-exception[snippets='http-request,http-response,response-fields']

=== 챌린지 삭제

챌린지를 삭제합니다.

삭제는 챌린지 시작 시간 전까지만 가능하며, 챌린지 주최자만 삭제할 수 있습니다.

operation::challenge/delete[snippets='http-request,http-response,response-fields']

==== 에러 응답

===== 챌린지가 존재하지 않는 경우 (403 Forbidden)

챌린지 주최자가 아닌 경우 챌린지를 삭제하려는 경우입니다.

operation::challenge/delete-forbidden-exception[snippets='http-request,http-response,response-fields']

===== 챌린지가 존재하지 않는 경우 (404 Not Found)

존재하지 않는 챌린지를 삭제하려는 경우입니다.

operation::challenge/delete-not-found-exception[snippets='http-request,http-response,response-fields']
