== 챌린지 API
:doctype: book
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:seclinks:

챌린지 정보 조회, 챌린지 생성, 챌린지 정보 수정을 수행하는 API 목록입니다.

=== 나의 챌린지 참여 목록 조회

현재 접속한 사용자가 참여하고 있는 챌린지 목록을 반환합니다.

operation::challenge/get-my-challenge-list[snippets='http-request,http-response,response-fields']

=== 챌린지 상세 정보 조회

첼린지의 상세 정보를 조회합니다.

참여 요일에 해당하는 `participatingDays` 는 비트 연산을 사용합니다.

7자리로 이루어진 2진수 `0000000` 를 기준으로 좌측부터 `일월화수목금토` 입니다.

예를 들어, `화요일`, `목요일` 이 챌린지 참여 날짜라면, 2진수로 `0010100` 이고, 10진수로 변환하면 `20` 이 됩니다.

HTTP response 예시에 나온 `participatingDays` 의 값 `4` 는 10진수 `4` 를 의미하고 2진수로 `0000011` 이기 때문에 `금요일` 과 `토요일` 이 챌린지 참여 요일이 됩니다.

operation::challenge/get-challenge-details[snippets='http-request,http-response,response-fields']

==== 에러 응답

===== 챌린지가 존재하지 않는 경우 (404 Not Found)

존재하지 않는 챌린지를 조회한 경우입니다.

operation::challenge/get-challenge-details-not-found-exception[snippets='http-request,http-response,response-fields']

=== 챌린지 생성

새로운 첼린지를 생성합니다.

operation::challenge/create-challenge[snippets='http-request,http-response,response-fields']

==== 에러 응답

===== 챌린지 시작 시간이 현재 시간보다 이전인 경우 (400 Bad Request)

챌린지 시작 시간이 현재 시간보다 이전인 경우입니다.

operation::challenge/create-challenge-invalid-start-time[snippets='http-request,http-response,response-fields']

=== 챌린지 정보 수정

챌린지 정보를 수정합니다.

operation::challenge/patch-challenge[snippets='http-request,http-response,response-fields']

==== 에러 응답

===== 챌린지 설명이 이전과 동일한 경우 (400 Bad Request)

챌린지 설명이 이전과 동일한 경우입니다.

operation::challenge/patch-challenge-duplicated-description-exception[snippets='http-request,http-response,response-fields']

===== 챌린지 주최자가 아닌 경우 (403 Forbidden)

챌린지 주최자가 아닌 경우입니다.

operation::challenge/patch-challenge-forbidden-exception[snippets='http-request,http-response,response-fields']

=== 챌린지 참여자 등록

사용자를 챌린지 참여자에 등록합니다.

operation::challenge/enroll-challenge[snippets='http-request,http-response,response-fields']

==== 에러 응답

===== 챌린지 등록 시간이 지난 경우 (400 Bad Request)

챌린지 시작 시간이 지나고 나서 등록하는 경우입니다.

operation::challenge/enroll-challenge-invalid-registration-time-exception[snippets='http-request,http-response,response-fields']

===== 이미 참여한 챌린지인 경우 (409 Conflict)

이미 챌린지에 등록한 사용자가 다시 챌린지 등록하는 신청한 경우입니다.

operation::challenge/enroll-challenge-already-enrolled-exception[snippets='http-request,http-response,response-fields']

=== 챌린지 등록 취소

등록한 챌린지를 취소합니다.

취소는 챌린지 시작 시간 이전까지만 가능합니다.

operation::challenge/cancel-challenge-enrollment[snippets='http-request,http-response,response-fields']
