== 챌린지 포스트 API
:doctype: book
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:seclinks:

챌린지 포스트를 등록, 조회, 수정 및 삭제할 수 있습니다.

Request Header 에는 ``Authorization: Bearer {access token}`` 와 같은 형식으로 보내야 하며, 사용자의 ``액세스 토큰``이 필요합니다.

=== 챌린지 포스트 조회

경로 변수로 받은 post의 id값을 이용해 특정 챌린지 포스트를 조회합니다.

operation::challengePost/get-challenge-post[snippets='http-request,http-response,response-fields']

=== 챌린지 내 전체 포스트 조회

경로 변수로 받은 challenge의 id값을 이용해 해당 챌린지 내의 모든 포스트를 조회합니다.
해당 챌린지에 등록되어 있는 멤버만 포스트를 조회할 수 있습니다.

(포스트 목록을 반환하는 뒤이은 모든 메서드가 그렇습니다만,) 복수의 포스트를 반환하는 API는 페이지네이션 메타 데이터와 함께 반환됩니다.

data의 content에는 포스트 뷰 객체가 배열로 담깁니다.

data의 pageable 객체에는 페이지네이션 정보가 담겨있습니다.
그러나 pageable 객체에 접근하지 않아도 바로 사용할 수 있는 메타 데이터가 추가로 존재합니다.
그렇기 때문에 프론트엔드에서 pageable 객체를 사용할 필요는 없을 듯 합니다.

data에서 content 배열, pageable 객체를 지나면 바로 페이징 메타 데이터가 존재합니다.
특히 현재 페이지가 마지막 페이지인지 boolean으로 알려주는 "last" 속성이 있으므로,
이를 활용할 수 있습니다.


operation::challengePost/get-challenge-posts[snippets='http-request,http-response,response-fields']

=== 챌린지 내 전체 포스트 중 공지 포스트 조회

경로 변수로 받은 challenge의 id값을 이용해 해당 챌린지 내의 모든 공지 포스트를 조회합니다.
해당 챌린지에 등록되어 있는 멤버만 조회할 수 있습니다.

operation::challengePost/get-announcement-challenge-posts[snippets='http-request,http-response,response-fields']

=== 챌린지 내 본인이 작성한 모든 포스트 조회

경로 변수로 받은 challenge의 id값을 이용해 해당 챌린지 내에서 본인이 작성한 모든 포스트를 조회합니다.
'본인'이란 요청을 보낸 멤버를 의미합니다.

operation::challengePost/get-challenge-posts-by-me[snippets='http-request,http-response,response-fields']

=== 챌린지 포스트 생성

경로 변수로 받은 challenge의 id값에 해당하는 챌린지에 포스트를 작성합니다.
챌린지의 호스트라면 공지 포스트를 작성할 수 있습니다.

operation::challengePost/create-challenge-post[snippets='http-request,http-response,request-fields,response-fields']

=== 챌린지 포스트 수정

경로 변수로 받은 post의 id값에 해당하는 포스트를 수정합니다.
수정은 포스트 내용 변경, 공지 포스트 여부 변경과 함께 포스트 내 이미지 파일의 추가, 삭제 및 정렬 순서 변경을 포함합니다.

operation::challengePost/patch-challenge-post[snippets='http-request,http-response,request-fields,response-fields']

=== 챌린지 포스트 삭제

경로 변수로 받은 post의 id값에 해당하는 포스트를 삭제합니다.
사실 일반 포스트는 삭제 기능을 제공하지 않기 때문에, 요청을 보내더라도 예외 처리됩니다.
공지 포스트만 챌린지 호스트가 삭제할 수 있습니다.

operation::challengePost/delete-challenge-post[snippets='http-request,http-response,response-fields']