== 사용자 API
:doctype: book
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:seclinks:

사용자의 정보를 조회 및 수정할 수 있습니다.

Request Header 에는 ``Authorization: Bearer {access token}`` 와 같은 형식으로 보내야 하며, 사용자의 ``액세스 토큰``이 필요합니다.

=== 사용자 조회

사용자의 정보를 조회합니다.

operation::member/get-member[snippets='http-request,http-response,response-fields']

=== 사용자 닉네임 변경

사용자의 닉네임을 변경합니다.

닉네임 규칙은 아래와 같습니다.

- 길이: 2~15자
- 문자: 영어 대소문자, 한글 (특수문자 제외)

operation::member/patch-member-nickname[snippets='http-request,http-response,response-fields']

==== 에러 응답

===== 1. 닉네임 규칙에 맞지 않는 경우 (400 Bad Request)

닉네임 규칙에 맞지 않는 경우입니다.

operation::member/patch-member-nickname-invalid-rule-exception[snippets='http-request,http-response,response-fields']

===== 2. 이전과 동일한 닉네임인 경우 (400 Bad Request)

이전에 사용했던 닉네임과 동일한 닉네임을 사용한 경우입니다.

operation::member/patch-member-nickname-duplicated-nickname-exception[snippets='http-request,http-response,response-fields']

=== 사용자 이미지 변경

사용자의 이미지를 변경합니다.

이미지 파일은 아래의 조건을 만족해야 합니다.

- 확장자: jpg, jpeg, png
- 크기: 1MB 이하

응답으로 반환되는 `preSignedUrl` 은 프론트엔드에서 S3 로 이미지를 직접 업로드 하기 위한 링크입니다.

operation::member/patch-member-image[snippets='http-request,http-response,response-fields']

==== 에러 응답

===== 1. 이미지 크기가 초과한 경우 (400 Bad Request)

이미지 크기가 1MB 초과한 경우입니다.

operation::member/patch-member-image-size-exceeded-exception[snippets='http-request,http-response,response-fields']

===== 2. 허용하지 않는 이미지 확장자인 경우 (400 Bad Request)

허용하는 이미지 확장자가 아닌 경우입니다.

operation::member/patch-member-image-unsupported-extension-exception[snippets='http-request,http-response,response-fields']

=== 회원 탈퇴

회원 탈퇴를 진행합니다.

반환되는 값은 DB 테이블의 Primary Key 에 해당하는 사용자의 ID 입니다.

operation::member/delete-member[snippets='http-request,http-response,response-fields']
